"""Generate the firmware's PROGMEM web bundle from canonical web files."""

from pathlib import Path


if "__file__" in globals():
    PROJECT_ROOT = Path(__file__).resolve().parents[1]
else:
    # PlatformIO/SCons executes extra scripts without defining __file__ and
    # sets the working directory to the project root.
    PROJECT_ROOT = Path.cwd().resolve()
WEB_ROOT = PROJECT_ROOT / "web"
HEADER_PATH = PROJECT_ROOT / "src" / "generated_web_assets.h"
SOURCE_PATH = PROJECT_ROOT / "src" / "generated_web_assets.cpp"
RAW_DELIMITER = "STRAWBERRY_ASSET"

ASSETS = (
    ("kHomePage", "index.html"),
    ("kLettersPage", "letters.html"),
    ("kTrackingPage", "track.html"),
    ("kAdminPage", "postie.html"),
    ("kDiagnosticsPage", "diagnostics.html"),
    ("kPublicStyles", "style.css"),
    ("kLogoSvg", "logo.svg"),
)


def read_asset(filename: str) -> str:
    content = (WEB_ROOT / filename).read_text(encoding="utf-8")
    closing_marker = f'){RAW_DELIMITER}"'
    if closing_marker in content:
        raise ValueError(f"{filename} contains reserved raw-string marker {closing_marker}")
    return content


def generated_outputs() -> dict[Path, str]:
    declarations = "\n".join(
        f"extern const char {symbol}[] PROGMEM;" for symbol, _ in ASSETS
    )
    definitions = "\n\n".join(
        f'const char {symbol}[] PROGMEM = R"{RAW_DELIMITER}({read_asset(filename)})'
        f'{RAW_DELIMITER}";'
        for symbol, filename in ASSETS
    )
    banner = "// Generated by tools/generate_web_assets.py. Do not edit manually.\n"
    header = (
        f"{banner}#pragma once\n\n#include <Arduino.h>\n\n"
        f"namespace WebAssets {{\n\n{declarations}\n\n}}  // namespace WebAssets\n"
    )
    source = (
        f'{banner}#include "generated_web_assets.h"\n\n'
        f"namespace WebAssets {{\n\n{definitions}\n\n}}  // namespace WebAssets\n"
    )
    return {HEADER_PATH: header, SOURCE_PATH: source}


def generate() -> None:
    for path, content in generated_outputs().items():
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        path.write_text(content, encoding="utf-8", newline="\n")
        print(f"Generated {path.relative_to(PROJECT_ROOT)}")


if "__file__" not in globals() or __name__ == "__main__":
    generate()
