// Generated by tools/generate_web_assets.py. Do not edit manually.
#include "generated_web_assets.h"

namespace WebAssets {

const char kHomePage[] PROGMEM = R"STRAWBERRY_ASSET(<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Notice Board | Strawberry Post</title>
  <link rel="stylesheet" href="/style.css">
</head>
<body>
  <main>
    <h1>Strawberry Post</h1>
    <p>Community notices and local letters, available here without internet.</p>

    <section class="board-heading">
      <div>
        <h2>Notice Board</h2>
        <p>See what people nearby have shared.</p>
      </div>
      <a class="letter-link" href="/letters">Send or track a letter</a>
    </section>

    <section id="posts" aria-label="Current notices">
      <p class="hint">Loading notices&hellip;</p>
    </section>

    <section class="post-form" aria-labelledby="post-heading">
      <h2 id="post-heading">Pin a notice</h2>
      <form id="notice-form">
        <label>Category
          <select name="category" required>
            <option value="" selected disabled>Choose a category</option>
            <option>General</option>
            <option>Missed Connection</option>
            <option>Lost &amp; Found</option>
            <option>Event / Schedule</option>
            <option>Ride Share</option>
            <option>Help Wanted</option>
            <option>For Sale / Swap</option>
          </select>
        </label>
        <p class="hint">Looking for someone you met? Choose &ldquo;Missed Connection&rdquo;.</p>
        <label>Message
          <textarea name="message" maxlength="512" required></textarea>
        </label>
        <button type="submit">Pin notice</button>
      </form>
      <p id="result" role="status"></p>
    </section>

    <p id="delivery-status" class="status" aria-live="polite">Loading delivery status&hellip;</p>
    <section class="stats" aria-label="Postal statistics">
      <div class="stat"><strong id="notices-active">&ndash;</strong>active notices</div>
      <div class="stat"><strong id="letters-waiting">&ndash;</strong>waiting letters</div>
      <div class="stat"><strong id="letters-delivered">&ndash;</strong>delivered</div>
    </section>
    <p class="hint">Connected to STRAWBERRY POST &mdash; no internet needed.</p>
  </main>
  <script>
    const posts = document.querySelector('#posts');
    const form = document.querySelector('#notice-form');
    const result = document.querySelector('#result');
    const text = (id, value) => { document.querySelector(id).textContent = value; };

    function element(tag, value) {
      const node = document.createElement(tag);
      node.textContent = value;
      return node;
    }

    async function loadNotices() {
      const response = await fetch('/api/notices');
      const data = await response.json();
      if (!data.notices.length) {
        posts.replaceChildren(element('p', 'No notices yet. Be the first to pin one.'));
        return;
      }
      posts.replaceChildren(...data.notices.map(notice => {
        const article = document.createElement('article');
        article.className = 'post';
        article.append(element('strong', notice.category), element('p', notice.message));
        return article;
      }));
    }

    async function loadStats() {
      const response = await fetch('/api/stats');
      const stats = await response.json();
      const out = stats.lettersOutForDelivery;
      text('#delivery-status', `${out} ${out === 1 ? 'letter' : 'letters'} currently out for delivery`);
      text('#letters-waiting', stats.lettersWaiting);
      text('#letters-delivered', stats.lettersDelivered);
      text('#notices-active', stats.noticesActive);
    }

    form.addEventListener('submit', async event => {
      event.preventDefault();
      result.textContent = 'Pinning notice...';
      const response = await fetch('/api/notices', {
        method: 'POST',
        headers: {'Content-Type': 'application/x-www-form-urlencoded'},
        body: new URLSearchParams(new FormData(form))
      });
      const data = await response.json();
      result.textContent = response.ok ? 'Your notice is now on the board.' : data.error;
      if (response.ok) {
        form.reset();
        await Promise.all([loadNotices(), loadStats()]);
      }
    });

    Promise.all([loadNotices(), loadStats()]).catch(() => {
      result.textContent = 'The board is temporarily unavailable.';
    });
  </script>
</body>
</html>
)STRAWBERRY_ASSET";

const char kLettersPage[] PROGMEM = R"STRAWBERRY_ASSET(<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Digital Letters | Strawberry Post</title>
  <link rel="stylesheet" href="/style.css">
</head>
<body>
  <main>
    <a class="back" href="/">&larr; Strawberry Post</a>
    <h1>Send a Digital Letter</h1>
    <p class="hint">Only the Postie can read your message. Keep the tracking code shown after sending.</p>
    <form id="send">
      <label>Who is it for?<input name="recipient" maxlength="120" required></label>
      <label>Where might we find them?<input name="location" maxlength="80" required></label>
      <label>Your message<textarea name="message" maxlength="500" required></textarea></label>
      <label>Your name (optional)<input name="sender" maxlength="80"></label>
      <button>Send to the Postie</button>
    </form>
    <p id="result" class="ticket" role="status" hidden></p>
    <h2>Track a letter</h2>
    <form id="track">
      <label>Tracking code<input name="tracking" maxlength="10" placeholder="STRAW-0427" required></label>
      <button>Check status</button>
    </form>
    <p id="status" role="status"></p>
  </main>
  <script>
    const send = document.querySelector('#send');
    const result = document.querySelector('#result');
    const track = document.querySelector('#track');
    const status = document.querySelector('#status');

    send.addEventListener('submit', async event => {
      event.preventDefault();
      const response = await fetch('/api/letters', {
        method: 'POST',
        headers: {'Content-Type': 'application/x-www-form-urlencoded'},
        body: new URLSearchParams(new FormData(send))
      });
      const data = await response.json();
      result.hidden = false;
      result.textContent = data.error || `Keep this tracking code: ${data.tracking}`;
      if (response.ok) send.reset();
    });

    track.addEventListener('submit', async event => {
      event.preventDefault();
      const code = new FormData(track).get('tracking');
      const response = await fetch(`/api/letters/status?tracking=${encodeURIComponent(code)}`);
      const data = await response.json();
      status.textContent = data.error || `${data.tracking}: ${data.status}`;
    });
  </script>
</body>
</html>
)STRAWBERRY_ASSET";

const char kAdminPage[] PROGMEM = R"STRAWBERRY_ASSET(<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Postie | Strawberry Post</title>
  <link rel="stylesheet" href="/style.css">
</head>
<body class="admin">
  <main>
    <h1>Postie&rsquo;s Sorting Room</h1>
    <p>This page and its APIs require Postie authentication.</p>
    <p><a href="/postie/diagnostics">System diagnostics</a></p>
    <h2>Letters</h2>
    <section id="letters"></section>
    <h2>Notice moderation</h2>
    <section id="notices"></section>
    <p id="result" role="status"></p>
  </main>
  <script>
    const result = document.querySelector('#result');
    function element(tag, text, className) {
      const node = document.createElement(tag);
      if (text !== undefined) node.textContent = text;
      if (className) node.className = className;
      return node;
    }

    async function post(url, data) {
      const response = await fetch(url, {
        method: 'POST',
        headers: {'Content-Type': 'application/x-www-form-urlencoded'},
        body: new URLSearchParams(data)
      });
      const body = await response.json();
      result.textContent = body.error || 'Saved.';
      if (response.ok) await load();
    }

    function actionButton(label, callback, className) {
      const button = element('button', label, className);
      button.onclick = callback;
      return button;
    }

    async function load() {
      const response = await fetch('/api/admin/overview');
      if (!response.ok) {
        result.textContent = 'Authentication failed.';
        return;
      }
      const data = await response.json();

      const letters = document.querySelector('#letters');
      letters.replaceChildren(...data.letters.map(letter => {
        const card = element('details', undefined, 'card');
        if (letter.status === 'Waiting') card.open = true;
        card.append(element('summary', `${letter.tracking} — ${letter.recipient} — ${letter.status}`));
        const details = element('dl', undefined, 'private');
        [['Likely location', letter.location], ['Message', letter.message], ['Sender', letter.sender || 'Anonymous']]
          .forEach(([label, value]) => details.append(element('dt', label), element('dd', value)));
        card.append(details);
        ['Written', 'OutForDelivery', 'Delivered', 'CouldNotFind'].forEach(status =>
          card.append(actionButton(status, () => post('/api/admin/letters/status', {id: letter.id, status}))));
        return card;
      }));

      const notices = document.querySelector('#notices');
      notices.replaceChildren(...data.notices.map(notice => {
        const card = element('article', undefined, 'card');
        card.append(
          element('strong', notice.category),
          element('p', notice.message),
          actionButton(notice.hidden ? 'Unhide' : 'Hide', () => post('/api/admin/notices/moderate', {
            id: notice.id,
            action: notice.hidden ? 'unhide' : 'hide'
          }), 'alt'),
          actionButton('Delete', () => post('/api/admin/notices/moderate', {id: notice.id, action: 'delete'}))
        );
        return card;
      }));
    }

    load().catch(() => { result.textContent = 'Could not load the sorting room.'; });
  </script>
</body>
</html>
)STRAWBERRY_ASSET";

const char kDiagnosticsPage[] PROGMEM = R"STRAWBERRY_ASSET(<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Diagnostics | Strawberry Post</title>
  <link rel="stylesheet" href="/style.css">
</head>
<body class="admin">
  <main>
    <p><a href="/postie">&larr; Sorting Room</a></p>
    <h1>System diagnostics</h1>
    <dl id="data" class="diagnostics"></dl>
    <p>Refresh this page while testing with multiple phones.</p>
    <p id="result" role="status"></p>
  </main>
  <script>
    fetch('/api/admin/diagnostics')
      .then(response => response.json())
      .then(data => {
        const list = document.querySelector('#data');
        Object.entries(data).forEach(([key, value]) => {
          const term = document.createElement('dt');
          const description = document.createElement('dd');
          term.textContent = key;
          description.textContent = value;
          list.append(term, description);
        });
      })
      .catch(() => { document.querySelector('#result').textContent = 'Could not load diagnostics.'; });
  </script>
</body>
</html>
)STRAWBERRY_ASSET";

const char kPublicStyles[] PROGMEM = R"STRAWBERRY_ASSET(:root {
  color-scheme: light;
  --red: #a92330;
  --deep: #55251f;
  --cream: #fff8e7;
  --paper: #fffdf5;
  --cork: #c79568;
  --muted: #78645b;
}

* { box-sizing: border-box; }

body {
  margin: 0;
  background: var(--cream);
  color: var(--deep);
  font: 17px/1.45 system-ui, -apple-system, sans-serif;
}

body::before {
  content: "";
  display: block;
  height: .55rem;
  background: repeating-linear-gradient(
    135deg,
    var(--red) 0 18px,
    var(--paper) 18px 36px,
    #315b6e 36px 54px,
    var(--paper) 54px 72px
  );
}

main {
  width: min(100% - 2rem, 42rem);
  margin: 0 auto;
  padding: 1.4rem 0 3rem;
}

h1, h2 { color: var(--red); line-height: 1.1; }
h1 {
  margin: .8rem 0;
  font-family: Georgia, serif;
  font-size: clamp(2.2rem, 10vw, 3.7rem);
  letter-spacing: -.03em;
}

a { color: var(--red); }
button {
  display: block;
  width: 100%;
  padding: 1rem;
  border: 0;
  border-radius: .5rem;
  background: var(--red);
  box-shadow: 0 3px 0 #71141d;
  color: #fff;
  font: 700 1.05rem system-ui;
  text-align: center;
  text-decoration: none;
}

button:active {
  transform: translateY(2px);
  box-shadow: 0 1px 0 #71141d;
}

.status, .ticket {
  padding: 1rem;
  border: 2px dashed var(--cork);
  background: var(--paper);
  text-align: center;
}

.stats {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: .6rem;
  margin-top: 1rem;
}

.stat {
  padding: .8rem;
  border: 1px solid #ead7bb;
  background: var(--paper);
  text-align: center;
}

.stat strong { display: block; color: var(--red); font-size: 1.5rem; }
label { display: block; margin: 1rem 0; font-weight: 700; }
input, select, textarea {
  display: block;
  width: 100%;
  margin-top: .35rem;
  padding: .85rem;
  border: 1px solid #b99b80;
  border-radius: .35rem;
  background: #fff;
  color: inherit;
  font: inherit;
}

textarea { min-height: 9rem; resize: vertical; }
.board-heading {
  display: flex;
  align-items: end;
  justify-content: space-between;
  gap: 1rem;
  margin-top: 1.5rem;
}
.board-heading h2, .board-heading p { margin: .25rem 0; }
.letter-link { font-weight: 700; white-space: nowrap; }
.post-form {
  margin: 2rem 0;
  padding: 1rem;
  border: 2px dashed var(--cork);
  background: #f8e8cb;
}
.post, .card {
  margin: 1rem 0;
  padding: 1rem;
  border-left: 5px solid var(--red);
  background: var(--paper);
  box-shadow: 0 2px 8px #6b3a2520;
}

.post p, .card p, .private dd { white-space: pre-wrap; }
.back { display: inline-block; margin: .4rem 0 1rem; }
.hint { color: var(--muted); font-size: .92rem; }
[hidden] { display: none !important; }

.admin main { width: min(100% - 2rem, 52rem); }
.admin button {
  display: inline-block;
  width: auto;
  margin: .35rem .35rem 0 0;
  padding: .55rem .8rem;
  font: inherit;
}
.admin button.alt { background: #65544a; box-shadow: 0 3px 0 #3d322c; }
.admin summary { cursor: pointer; font-weight: 700; }
.admin dt { margin-top: .5rem; font-weight: 700; }
.admin dd { margin-left: 0; }
.private { padding-left: .8rem; border-left: 5px solid var(--red); }
.diagnostics {
  display: grid;
  grid-template-columns: minmax(0, 1fr) minmax(0, 1fr);
  gap: .4rem 1rem;
  padding: 1rem;
  background: var(--paper);
}
.diagnostics dt { overflow-wrap: anywhere; }
.diagnostics dd { margin: 0; overflow-wrap: anywhere; text-align: right; }

@media (min-width: 38rem) {
  .stats { grid-template-columns: repeat(3, 1fr); }
}

@media (max-width: 30rem) {
  .board-heading { align-items: start; flex-direction: column; }
}
)STRAWBERRY_ASSET";

}  // namespace WebAssets
