// Generated by tools/generate_web_assets.py. Do not edit manually.
#pragma once

#include <Arduino.h>

namespace WebAssets {

extern const char kHomePage[] PROGMEM;
extern const char kLettersPage[] PROGMEM;
extern const char kTrackingPage[] PROGMEM;
extern const char kAdminPage[] PROGMEM;
extern const char kDiagnosticsPage[] PROGMEM;
extern const char kPublicStyles[] PROGMEM;
extern const char kLogoSvg[] PROGMEM;

}  // namespace WebAssets
